spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/eva_ustc/tensquare_dev.git
  rabbitmq:
    host: 192.168.56.101
server:
  port: 12000
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh