server:
  port: 9006
spring:
  application:
    name: tensquare_spit
  data:
    mongodb:
      host: 192.168.56.101
      database: spitdb
  redis:
    host: 192.168.56.101
  rabbitmq:
    host: 192.168.56.101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true